CREATE TABLE IF NOT EXISTS `page_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `page_key` VARCHAR(64) NOT NULL,
  `body_html` MEDIUMTEXT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `page_content_key_unique` (`page_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
